web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - ./web:/usr/src/app
  env_file: .env
  command: /usr/local/bin/daphne -b :8000 alkemata.asgi:channel_layer

 worker:
  build: .
  command: python manage.py runworker
  volumes:
   - .:/code
  links:
   - redis

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web
    - jupyter:jupyter

postgres:
  restart: always
  env_file: .env
  image: postgres:latest
  volumes:
    - /mnt/vdb/database:/var/lib/postgresql/data
  ports:
    - "5432:5432"

redis:
  image: redis:3.0-alpine

jupyter:
  build: ./jupyter/
  restart: always
  ports:
    - "8888:8888"
  volumes:
    - /mnt/vdb/notebooks:/home/jovyan/notebooks
  command: jupyter kernelgateway --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.port=8888
